// Copyright (C) 1991-2015 Altera Corporation. All rights reserved.
// Your use of Altera Corporation's design tools, logic functions 
// and other software and tools, and its AMPP partner logic 
// functions, and any output files from any of the foregoing 
// (including device programming or simulation files), and any 
// associated documentation or information are expressly subject 
// to the terms and conditions of the Altera Program License 
// Subscription Agreement, the Altera Quartus Prime License Agreement,
// the Altera MegaCore Function License Agreement, or other 
// applicable license agreement, including, without limitation, 
// that your use is for the sole purpose of programming logic 
// devices manufactured by Altera and sold by Altera or its 
// authorized distributors.  Please refer to the applicable 
// agreement for further details.


// Generated by Quartus Prime Version 15.1 (Build Build 185 10/21/2015)
// Created on Wed Mar 22 20:10:23 2017

ALU ALU_inst
(
	.op_a(op_a_sig) ,	// input [31:0] op_a_sig
	.op_b(op_b_sig) ,	// input [31:0] op_b_sig
	.out(out_sig) ,	// output [31:0] out_sig
	.op_code(op_code_sig) ,	// input [4:0] op_code_sig
	.flag_carry(flag_carry_sig) ,	// output  flag_carry_sig
	.flag_overflow(flag_overflow_sig) ,	// output  flag_overflow_sig
	.flag_parity(flag_parity_sig) ,	// output  flag_parity_sig
	.flag_neg(flag_neg_sig) 	// output  flag_neg_sig
);

